### ISSUE TITLE
TODO - Checklist

### ISSUE THREAD

**Issue by pascal-chenevas** [pascal-chenevas/carbone_sdk_rs#1]
# http response headers

- [ ] add functionalities + test to fetch filename of a template from the header of a response
## Code

- [ ] check usage of TemplateId.as_ref() instead of TemplateId ?

### Render

- [ ]  RenderOptions check for deserialization with serde
- [ ] rename RenderOption struct to JsonData 
- [ ]  impl FromStr for render_options 

## Tests

- [ ]  check for code duplication in async / blocking => refactoring
- [ ] extract mock fn in its own file like (rename Helper -> mock?)

- [ ] check order left / right by assertion

--- 

- [ ] add test_render_a_report_from_an_existing_template_id()
- [ ] add test_render_from_a_template_already_uploaded()
- [ ] add test_render_a_report_from_a_new_template()

---
 
## Documentation

- [ ] add a comment for each function
- [ ] comments must include code examples so that the documentation can be [tested] (https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html)
- [ ] Update README.md with content (how to use/install the lib)
